Create local account
opixelum/vault pull request #29
Opened 2023-02-05 14:43 UTC by opixelum

- Local account is needed for using the app
- App manages only 1 local account
- Local account is just a password (no username needed)
- Local account password is stored is `local_account` file at the root of the app directory
- This file contains the salt used for local account creation & the sha512 hash of the password
- Manage local account added in main menu
- Manage local account menu is for changing local account password and for deleting local account

2023-02-05 21:00 UTC, Invorom requested changes

2023-02-05 21:00 UTC, Invorom commented on lib/local_account.c
> +    fprintf(local_account_file, "%s\n", salt);
Need to encrypt salt

2023-02-05 21:00 UTC, Invorom commented on lib/local_account.c
> +    char *salt = malloc(sizeof *salt * SALT_LENGTH);
Change this if salt is encrypted

2023-02-05 21:00 UTC, Invorom commented on lib/local_account.c
> +    // Compare password hashes
Need to precise hexa

2023-02-05 21:00 UTC, Invorom commented on lib/ui.c
> +unsigned char getCharHide()
U need to comment

2023-02-05 21:00 UTC, Invorom commented on lib/ui.c
> +        exit(EXIT_FAILURE);
Need to review errors management

2023-02-05 21:00 UTC, Invorom commented on lib/ui.c
> +        c = getCharHide();
Change variable name

2023-02-05 21:00 UTC, Invorom commented on lib/ui.c
> +        else if (c == 127 || c == 8) // Handle del & backspace
Del: right --> left
Suppr: left --> right

2023-02-05 21:00 UTC, Invorom commented on lib/ui.c
> +    while (string_length < 1024);
BONUS: Block user from send more than 1024
Example: Red, or vibrations when the length is reached

2023-02-05 21:00 UTC, Invorom commented on lib/ui.c
> +    int c;
Variable name

2023-02-05 21:00 UTC, Invorom commented on lib/ui.c
> +            printf("\nPassword doesn't respect the minimum requirements:\n- Length >= 12\n- At least one uppercase\n- At least one lowercase\n- At least one digit\n- At least one special character.\n
BONUS: Need to precise error type
User-friendly :)

2023-02-05 21:00 UTC, Invorom commented on lib/ui.c
> +    while (local_account_login_status != 0);
BONUS: Implement blocked time if wrong

2023-02-05 21:00 UTC, Invorom commented on lib/ui.c
> +
Delete this ugly useless line

2023-02-05 21:00 UTC, Invorom commented on lib/ui.c
> +    char is_current_password_correct = 0;
BONUS: Add "Forgot my password" --> Need to save user email

2023-02-05 21:00 UTC, Invorom commented on lib/ui.c
> +    char is_current_password_correct = 0;
And modify email in manage locale account

2023-02-05 21:00 UTC, Invorom commented on lib/ui.c
> +}
BONUS: Refacto code and use only one function for change and create password

2023-02-05 21:00 UTC, Invorom commented on lib/ui.c
> +    printf("\nDelete local account\n\nPLEASE NOTE THAT THIS ACTION WILL DELETE ALL YOUR CREDENTIALS AND IS IRREVERSIBLE.\n\n");
/!\

2023-02-05 21:00 UTC, Invorom commented on src/main.c
>  #include <unistd.h>
Idk, need to test

2023-02-05 21:00 UTC, Invorom commented on src/main.c
> +            isConnected = 1;
Error management

2023-02-05 21:20 UTC, Invorom requested changes
BUG: - Create local account
                - Press enter without text
                - Type something different than digits, letters; specials (del, arrows, f12, ...)

2023-02-06 22:19 UTC, opixelum commented on lib/local_account.c
> +    fprintf(local_account_file, "%s\n", salt);
#37

2023-02-06 22:19 UTC, opixelum commented on lib/local_account.c
> +    char *salt = malloc(sizeof *salt * SALT_LENGTH);
Will be done in #37

2023-02-06 22:26 UTC, opixelum commented on lib/local_account.c
> +    // Compare password hashes
Done in commit 4a0f70f

2023-02-06 23:02 UTC, opixelum commented on lib/ui.c
> +unsigned char getCharHide()
Done in commit a57eed1

2023-02-06 23:02 UTC, opixelum commented on lib/ui.c
> +        exit(EXIT_FAILURE);
Will be done in #33

2023-02-08 09:44 UTC, Invorom approved these changes

2023-02-08 09:45 UTC, merged